version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django-container
    networks:
      - django-network
  psql:
    extends:
      file: docker-compose-postgres.yml
      service: psql

  django-container:
    extends:
      file: docker-compose-django.yml
      service: django-container
  

networks:
  django-network:
    driver: bridge


volumes:
  psdb:
